version: "3"

services:
  php:
    build: .docker/php
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./.docker/nginx/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public
    depends_on:
      - php

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
